check-interval: 1
timers:
  gaming:
    apps:
      - retroarch
      - minecraft
    # how many minutes of usage
    time-limit: 60
    # within how many hours of interval
    limit-interval: 12
  pomodoro:
    apps:
      - atom
      - sublime_text
    time-limit: 30
    limit-interval: 45
